In [ ]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
image=cv2.imread("puppy_dog.jpg")
pts_src=np.array([[100,150],[200,150],[200,300],[100,250]],dtype='float32')
pts_dst=np.array([[50,100],[250,100],[200,300],[150,300]],dtype='float32')
homography_matrix,status=cv2.findHomography(pts_src,pts_dst)
print(homography_matrix)


height,width=image.shape[:2]
warped_image=cv2.warpPerspective(image,homography_matrix,(width,height))
cv2.imshow("warped",warped_image)
cv2.imshow('original',image)
cv2.waitKey(0)
cv2.destoryAllWindows()

[[-8.125e-01 -1.375e+00  2.750e+02]
 [-1.250e-01 -2.750e+00  4.000e+02]
 [-1.250e-03 -7.500e-03  1.000e+00]]
